# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'finalproject.ui',
# licensing of 'finalproject.ui' applies.
#
# Created: Wed Jan 16 11:00:21 2019
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(591, 590)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Pictures/1200px-Biopython_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("Resources/biopython+logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.entreznucleotide = QtWidgets.QWidget()
        self.entreznucleotide.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.entreznucleotide.setObjectName("entreznucleotide")
        self.formLayout_2 = QtWidgets.QFormLayout(self.entreznucleotide)
        self.formLayout_2.setObjectName("formLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_id = QtWidgets.QLabel(self.entreznucleotide)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_id.setFont(font)
        self.label_id.setObjectName("label_id")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_id)
        self.entrez_id = QtWidgets.QTextEdit(self.entreznucleotide)
        self.entrez_id.setMaximumSize(QtCore.QSize(300, 25))
        self.entrez_id.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entrez_id.setObjectName("entrez_id")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.entrez_id)
        self.label_email = QtWidgets.QLabel(self.entreznucleotide)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_email.setFont(font)
        self.label_email.setObjectName("label_email")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_email)
        self.entrez_email = QtWidgets.QTextEdit(self.entreznucleotide)
        self.entrez_email.setMaximumSize(QtCore.QSize(300, 25))
        self.entrez_email.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entrez_email.setObjectName("entrez_email")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.entrez_email)
        self.entrez_info_2 = QtWidgets.QPushButton(self.entreznucleotide)
        self.entrez_info_2.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setWeight(75)
        font.setBold(True)
        self.entrez_info_2.setFont(font)
        self.entrez_info_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entrez_info_2.setObjectName("entrez_info_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.entrez_info_2)
        self.formLayout_2.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.formLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(40, -1, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_type = QtWidgets.QLabel(self.entreznucleotide)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_type.setFont(font)
        self.label_type.setObjectName("label_type")
        self.horizontalLayout_4.addWidget(self.label_type)
        self.spinner = QtWidgets.QComboBox(self.entreznucleotide)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinner.sizePolicy().hasHeightForWidth())
        self.spinner.setSizePolicy(sizePolicy)
        self.spinner.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.spinner.setFont(font)
        self.spinner.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.spinner.setObjectName("spinner")
        self.spinner.addItem("")
        self.spinner.addItem("")
        self.horizontalLayout_4.addWidget(self.spinner)
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_4)
        self.entrez_fetch = QtWidgets.QPushButton(self.entreznucleotide)
        self.entrez_fetch.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entrez_fetch.sizePolicy().hasHeightForWidth())
        self.entrez_fetch.setSizePolicy(sizePolicy)
        self.entrez_fetch.setMinimumSize(QtCore.QSize(100, 25))
        self.entrez_fetch.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.entrez_fetch.setFont(font)
        self.entrez_fetch.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entrez_fetch.setObjectName("entrez_fetch")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.entrez_fetch)
        self.entrez_info = QtWidgets.QTextEdit(self.entreznucleotide)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.entrez_info.sizePolicy().hasHeightForWidth())
        self.entrez_info.setSizePolicy(sizePolicy)
        self.entrez_info.setMinimumSize(QtCore.QSize(0, 250))
        self.entrez_info.setMaximumSize(QtCore.QSize(16777215, 250))
        self.entrez_info.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entrez_info.setObjectName("entrez_info")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.entrez_info)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, -1, 150, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.entrez_clear = QtWidgets.QPushButton(self.entreznucleotide)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setWeight(75)
        font.setBold(True)
        self.entrez_clear.setFont(font)
        self.entrez_clear.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entrez_clear.setObjectName("entrez_clear")
        self.horizontalLayout_3.addWidget(self.entrez_clear)
        self.entrez_save = QtWidgets.QPushButton(self.entreznucleotide)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setWeight(75)
        font.setBold(True)
        self.entrez_save.setFont(font)
        self.entrez_save.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.entrez_save.setObjectName("entrez_save")
        self.horizontalLayout_3.addWidget(self.entrez_save)
        self.formLayout_2.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.tabWidget.addTab(self.entreznucleotide, "")
        self.sequenceparsing = QtWidgets.QWidget()
        self.sequenceparsing.setObjectName("sequenceparsing")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.sequenceparsing)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.sequenceparsing)
        self.scrollArea.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 683, 852))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.importbutton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.importbutton.setMaximumSize(QtCore.QSize(200, 35))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setWeight(75)
        font.setBold(True)
        self.importbutton.setFont(font)
        self.importbutton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.importbutton.setObjectName("importbutton")
        self.horizontalLayout_2.addWidget(self.importbutton)
        self.analyzebutton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.analyzebutton.setMaximumSize(QtCore.QSize(200, 35))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setWeight(75)
        font.setBold(True)
        self.analyzebutton.setFont(font)
        self.analyzebutton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.analyzebutton.setObjectName("analyzebutton")
        self.horizontalLayout_2.addWidget(self.analyzebutton)
        self.gridLayout_4.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelid = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.labelid.setFont(font)
        self.labelid.setObjectName("labelid")
        self.gridLayout_3.addWidget(self.labelid, 0, 0, 1, 1)
        self.id = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.id.sizePolicy().hasHeightForWidth())
        self.id.setSizePolicy(sizePolicy)
        self.id.setMinimumSize(QtCore.QSize(200, 30))
        self.id.setMaximumSize(QtCore.QSize(200, 30))
        self.id.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.id.setObjectName("id")
        self.gridLayout_3.addWidget(self.id, 0, 1, 1, 1)
        self.labeldescription = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.labeldescription.setFont(font)
        self.labeldescription.setObjectName("labeldescription")
        self.gridLayout_3.addWidget(self.labeldescription, 1, 0, 1, 1)
        self.labelseqalphabet = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.labelseqalphabet.setFont(font)
        self.labelseqalphabet.setObjectName("labelseqalphabet")
        self.gridLayout_3.addWidget(self.labelseqalphabet, 2, 0, 1, 1)
        self.recordsequence = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recordsequence.sizePolicy().hasHeightForWidth())
        self.recordsequence.setSizePolicy(sizePolicy)
        self.recordsequence.setMinimumSize(QtCore.QSize(500, 175))
        self.recordsequence.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.recordsequence.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.recordsequence.setObjectName("recordsequence")
        self.gridLayout_3.addWidget(self.recordsequence, 3, 1, 1, 1)
        self.labelsequencelength = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.labelsequencelength.setFont(font)
        self.labelsequencelength.setObjectName("labelsequencelength")
        self.gridLayout_3.addWidget(self.labelsequencelength, 4, 0, 1, 1)
        self.labelcomplementsequence = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.labelcomplementsequence.setFont(font)
        self.labelcomplementsequence.setObjectName("labelcomplementsequence")
        self.gridLayout_3.addWidget(self.labelcomplementsequence, 6, 0, 1, 1)
        self.complementsequence = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.complementsequence.sizePolicy().hasHeightForWidth())
        self.complementsequence.setSizePolicy(sizePolicy)
        self.complementsequence.setMinimumSize(QtCore.QSize(500, 175))
        self.complementsequence.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.complementsequence.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.complementsequence.setObjectName("complementsequence")
        self.gridLayout_3.addWidget(self.complementsequence, 6, 1, 1, 1)
        self.seqalphabet = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seqalphabet.sizePolicy().hasHeightForWidth())
        self.seqalphabet.setSizePolicy(sizePolicy)
        self.seqalphabet.setMinimumSize(QtCore.QSize(500, 35))
        self.seqalphabet.setMaximumSize(QtCore.QSize(1000, 25))
        self.seqalphabet.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.seqalphabet.setObjectName("seqalphabet")
        self.gridLayout_3.addWidget(self.seqalphabet, 2, 1, 1, 1)
        self.labeltotalaminoacid = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.labeltotalaminoacid.setFont(font)
        self.labeltotalaminoacid.setObjectName("labeltotalaminoacid")
        self.gridLayout_3.addWidget(self.labeltotalaminoacid, 5, 0, 1, 1)
        self.sequencelength = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sequencelength.sizePolicy().hasHeightForWidth())
        self.sequencelength.setSizePolicy(sizePolicy)
        self.sequencelength.setMinimumSize(QtCore.QSize(0, 0))
        self.sequencelength.setMaximumSize(QtCore.QSize(200, 30))
        self.sequencelength.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sequencelength.setObjectName("sequencelength")
        self.gridLayout_3.addWidget(self.sequencelength, 4, 1, 1, 1)
        self.labelreversecomplement = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.labelreversecomplement.setFont(font)
        self.labelreversecomplement.setObjectName("labelreversecomplement")
        self.gridLayout_3.addWidget(self.labelreversecomplement, 7, 0, 1, 1)
        self.labelsequence = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.labelsequence.setFont(font)
        self.labelsequence.setObjectName("labelsequence")
        self.gridLayout_3.addWidget(self.labelsequence, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.aminoacidbutton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.aminoacidbutton.setMaximumSize(QtCore.QSize(200, 35))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setWeight(75)
        font.setBold(True)
        self.aminoacidbutton.setFont(font)
        self.aminoacidbutton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.aminoacidbutton.setDefault(False)
        self.aminoacidbutton.setObjectName("aminoacidbutton")
        self.horizontalLayout_5.addWidget(self.aminoacidbutton)
        self.clearbutton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.clearbutton.setMaximumSize(QtCore.QSize(200, 35))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setWeight(75)
        font.setBold(True)
        self.clearbutton.setFont(font)
        self.clearbutton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.clearbutton.setObjectName("clearbutton")
        self.horizontalLayout_5.addWidget(self.clearbutton)
        self.savebutton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.savebutton.setMaximumSize(QtCore.QSize(200, 35))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setWeight(75)
        font.setBold(True)
        self.savebutton.setFont(font)
        self.savebutton.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.savebutton.setObjectName("savebutton")
        self.horizontalLayout_5.addWidget(self.savebutton)
        self.gridLayout_3.addLayout(self.horizontalLayout_5, 9, 1, 1, 1)
        self.totalaminoacid = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.totalaminoacid.sizePolicy().hasHeightForWidth())
        self.totalaminoacid.setSizePolicy(sizePolicy)
        self.totalaminoacid.setMinimumSize(QtCore.QSize(200, 30))
        self.totalaminoacid.setMaximumSize(QtCore.QSize(200, 30))
        self.totalaminoacid.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.totalaminoacid.setObjectName("totalaminoacid")
        self.gridLayout_3.addWidget(self.totalaminoacid, 5, 1, 1, 1)
        self.description = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.description.sizePolicy().hasHeightForWidth())
        self.description.setSizePolicy(sizePolicy)
        self.description.setMinimumSize(QtCore.QSize(500, 30))
        self.description.setMaximumSize(QtCore.QSize(1000, 25))
        self.description.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.description.setObjectName("description")
        self.gridLayout_3.addWidget(self.description, 1, 1, 1, 1)
        self.reversecomplement = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.reversecomplement.sizePolicy().hasHeightForWidth())
        self.reversecomplement.setSizePolicy(sizePolicy)
        self.reversecomplement.setMinimumSize(QtCore.QSize(500, 175))
        self.reversecomplement.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.reversecomplement.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.reversecomplement.setObjectName("reversecomplement")
        self.gridLayout_3.addWidget(self.reversecomplement, 7, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 3, 0, 1, 2)
        self.labelimport = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.labelimport.setFont(font)
        self.labelimport.setObjectName("labelimport")
        self.gridLayout_4.addWidget(self.labelimport, 0, 0, 1, 3)
        self.insertbox = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.insertbox.setMaximumSize(QtCore.QSize(200, 35))
        self.insertbox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.insertbox.setObjectName("insertbox")
        self.gridLayout_4.addWidget(self.insertbox, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.sequenceparsing, "")
        self.pairwise2 = QtWidgets.QWidget()
        self.pairwise2.setStyleSheet("background-color: rgb(170, 255, 255);")
        self.pairwise2.setObjectName("pairwise2")
        self.formLayout_4 = QtWidgets.QFormLayout(self.pairwise2)
        self.formLayout_4.setObjectName("formLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_mode = QtWidgets.QLabel(self.pairwise2)
        self.label_mode.setMinimumSize(QtCore.QSize(100, 0))
        self.label_mode.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_mode.setFont(font)
        self.label_mode.setObjectName("label_mode")
        self.horizontalLayout_6.addWidget(self.label_mode)
        self.radiobutton_import = QtWidgets.QRadioButton(self.pairwise2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(8)
        font.setWeight(75)
        font.setBold(True)
        self.radiobutton_import.setFont(font)
        self.radiobutton_import.setChecked(False)
        self.radiobutton_import.setObjectName("radiobutton_import")
        self.horizontalLayout_6.addWidget(self.radiobutton_import)
        self.radiobutton_manual = QtWidgets.QRadioButton(self.pairwise2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setWeight(75)
        font.setBold(True)
        self.radiobutton_manual.setFont(font)
        self.radiobutton_manual.setCheckable(True)
        self.radiobutton_manual.setChecked(False)
        self.radiobutton_manual.setObjectName("radiobutton_manual")
        self.horizontalLayout_6.addWidget(self.radiobutton_manual)
        self.formLayout_4.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_6)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_seq1 = QtWidgets.QLabel(self.pairwise2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_seq1.setFont(font)
        self.label_seq1.setObjectName("label_seq1")
        self.gridLayout_5.addWidget(self.label_seq1, 0, 0, 1, 1)
        self.seq1 = QtWidgets.QTextEdit(self.pairwise2)
        self.seq1.setMaximumSize(QtCore.QSize(16777215, 35))
        self.seq1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.seq1.setObjectName("seq1")
        self.gridLayout_5.addWidget(self.seq1, 0, 1, 1, 1)
        self.import_seq1 = QtWidgets.QPushButton(self.pairwise2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setWeight(75)
        font.setBold(True)
        self.import_seq1.setFont(font)
        self.import_seq1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.import_seq1.setObjectName("import_seq1")
        self.gridLayout_5.addWidget(self.import_seq1, 0, 2, 1, 1)
        self.label_seq2 = QtWidgets.QLabel(self.pairwise2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_seq2.setFont(font)
        self.label_seq2.setObjectName("label_seq2")
        self.gridLayout_5.addWidget(self.label_seq2, 1, 0, 1, 1)
        self.seq2 = QtWidgets.QTextEdit(self.pairwise2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.seq2.sizePolicy().hasHeightForWidth())
        self.seq2.setSizePolicy(sizePolicy)
        self.seq2.setMaximumSize(QtCore.QSize(16777215, 35))
        self.seq2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.seq2.setObjectName("seq2")
        self.gridLayout_5.addWidget(self.seq2, 1, 1, 1, 1)
        self.import_seq2 = QtWidgets.QPushButton(self.pairwise2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setWeight(75)
        font.setBold(True)
        self.import_seq2.setFont(font)
        self.import_seq2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.import_seq2.setObjectName("import_seq2")
        self.gridLayout_5.addWidget(self.import_seq2, 1, 2, 1, 1)
        self.formLayout_4.setLayout(1, QtWidgets.QFormLayout.SpanningRole, self.gridLayout_5)
        self.align = QtWidgets.QPushButton(self.pairwise2)
        self.align.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.align.setFont(font)
        self.align.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.align.setObjectName("align")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.align)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.alignment_label = QtWidgets.QLabel(self.pairwise2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.alignment_label.setFont(font)
        self.alignment_label.setObjectName("alignment_label")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.alignment_label)
        self.alignment_result = QtWidgets.QTextEdit(self.pairwise2)
        self.alignment_result.setMinimumSize(QtCore.QSize(0, 100))
        self.alignment_result.setMaximumSize(QtCore.QSize(16777215, 100))
        self.alignment_result.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.alignment_result.setObjectName("alignment_result")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.alignment_result)
        self.var_alignment_label = QtWidgets.QLabel(self.pairwise2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.var_alignment_label.setFont(font)
        self.var_alignment_label.setObjectName("var_alignment_label")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.var_alignment_label)
        self.variable_alignment = QtWidgets.QTextEdit(self.pairwise2)
        self.variable_alignment.setMaximumSize(QtCore.QSize(50, 25))
        self.variable_alignment.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.variable_alignment.setObjectName("variable_alignment")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.variable_alignment)
        self.list_alignment_label = QtWidgets.QLabel(self.pairwise2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setWeight(75)
        font.setBold(True)
        self.list_alignment_label.setFont(font)
        self.list_alignment_label.setObjectName("list_alignment_label")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.list_alignment_label)
        self.list_alignment = QtWidgets.QTextEdit(self.pairwise2)
        self.list_alignment.setMinimumSize(QtCore.QSize(0, 150))
        self.list_alignment.setMaximumSize(QtCore.QSize(16777215, 150))
        self.list_alignment.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.list_alignment.setObjectName("list_alignment")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.list_alignment)
        self.formLayout_4.setLayout(3, QtWidgets.QFormLayout.SpanningRole, self.formLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(19)
        self.horizontalLayout_7.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pairwise_clear = QtWidgets.QPushButton(self.pairwise2)
        self.pairwise_clear.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setWeight(75)
        font.setBold(True)
        self.pairwise_clear.setFont(font)
        self.pairwise_clear.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pairwise_clear.setObjectName("pairwise_clear")
        self.horizontalLayout_7.addWidget(self.pairwise_clear)
        self.pairwise_save = QtWidgets.QPushButton(self.pairwise2)
        self.pairwise_save.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setWeight(75)
        font.setBold(True)
        self.pairwise_save.setFont(font)
        self.pairwise_save.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pairwise_save.setObjectName("pairwise_save")
        self.horizontalLayout_7.addWidget(self.pairwise_save)
        self.formLayout_4.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_7)
        self.tabWidget.addTab(self.pairwise2, "")
        self.pubmedlounge = QtWidgets.QWidget()
        self.pubmedlounge.setObjectName("pubmedlounge")
        self.formLayout_6 = QtWidgets.QFormLayout(self.pubmedlounge)
        self.formLayout_6.setObjectName("formLayout_6")
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.labem_pmid_number = QtWidgets.QLabel(self.pubmedlounge)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.labem_pmid_number.setFont(font)
        self.labem_pmid_number.setObjectName("labem_pmid_number")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labem_pmid_number)
        self.pmid = QtWidgets.QTextEdit(self.pubmedlounge)
        self.pmid.setMaximumSize(QtCore.QSize(300, 25))
        self.pmid.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pmid.setObjectName("pmid")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pmid)
        self.label_pmid_email = QtWidgets.QLabel(self.pubmedlounge)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_pmid_email.setFont(font)
        self.label_pmid_email.setObjectName("label_pmid_email")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_pmid_email)
        self.pmid_email = QtWidgets.QTextEdit(self.pubmedlounge)
        self.pmid_email.setMaximumSize(QtCore.QSize(300, 25))
        self.pmid_email.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pmid_email.setObjectName("pmid_email")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.pmid_email)
        self.pmid_info = QtWidgets.QPushButton(self.pubmedlounge)
        self.pmid_info.setMaximumSize(QtCore.QSize(75, 16777215))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setWeight(75)
        font.setBold(True)
        self.pmid_info.setFont(font)
        self.pmid_info.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pmid_info.setObjectName("pmid_info")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.pmid_info)
        self.formLayout_6.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.formLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(24, -1, -1, -1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_type_2 = QtWidgets.QLabel(self.pubmedlounge)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_type_2.setFont(font)
        self.label_type_2.setObjectName("label_type_2")
        self.horizontalLayout_8.addWidget(self.label_type_2)
        self.pmid_spinner = QtWidgets.QComboBox(self.pubmedlounge)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pmid_spinner.sizePolicy().hasHeightForWidth())
        self.pmid_spinner.setSizePolicy(sizePolicy)
        self.pmid_spinner.setMinimumSize(QtCore.QSize(100, 25))
        self.pmid_spinner.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.pmid_spinner.setFont(font)
        self.pmid_spinner.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pmid_spinner.setObjectName("pmid_spinner")
        self.pmid_spinner.addItem("")
        self.pmid_spinner.addItem("")
        self.pmid_spinner.addItem("")
        self.horizontalLayout_8.addWidget(self.pmid_spinner)
        self.formLayout_6.setLayout(1, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_8)
        self.pmid_fetch = QtWidgets.QPushButton(self.pubmedlounge)
        self.pmid_fetch.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pmid_fetch.sizePolicy().hasHeightForWidth())
        self.pmid_fetch.setSizePolicy(sizePolicy)
        self.pmid_fetch.setMinimumSize(QtCore.QSize(100, 25))
        self.pmid_fetch.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.pmid_fetch.setFont(font)
        self.pmid_fetch.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pmid_fetch.setObjectName("pmid_fetch")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pmid_fetch)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(200, -1, 0, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pmid_clear = QtWidgets.QPushButton(self.pubmedlounge)
        self.pmid_clear.setMinimumSize(QtCore.QSize(100, 25))
        self.pmid_clear.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setWeight(75)
        font.setBold(True)
        self.pmid_clear.setFont(font)
        self.pmid_clear.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pmid_clear.setObjectName("pmid_clear")
        self.horizontalLayout_9.addWidget(self.pmid_clear)
        self.pmid_save = QtWidgets.QPushButton(self.pubmedlounge)
        self.pmid_save.setMinimumSize(QtCore.QSize(100, 25))
        self.pmid_save.setMaximumSize(QtCore.QSize(100, 35))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setWeight(75)
        font.setBold(True)
        self.pmid_save.setFont(font)
        self.pmid_save.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pmid_save.setObjectName("pmid_save")
        self.horizontalLayout_9.addWidget(self.pmid_save)
        self.formLayout_6.setLayout(4, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout_9)
        self.pmid_data = QtWidgets.QTextEdit(self.pubmedlounge)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pmid_data.sizePolicy().hasHeightForWidth())
        self.pmid_data.setSizePolicy(sizePolicy)
        self.pmid_data.setMinimumSize(QtCore.QSize(0, 250))
        self.pmid_data.setMaximumSize(QtCore.QSize(16777215, 250))
        self.pmid_data.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pmid_data.setObjectName("pmid_data")
        self.formLayout_6.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.pmid_data)
        self.tabWidget.addTab(self.pubmedlounge, "")
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 591, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QObject.connect(self.clearbutton, QtCore.SIGNAL("clicked()"), self.sequencelength.clear)
        QtCore.QObject.connect(self.clearbutton, QtCore.SIGNAL("clicked()"), self.recordsequence.clear)
        QtCore.QObject.connect(self.clearbutton, QtCore.SIGNAL("clicked()"), self.description.clear)
        QtCore.QObject.connect(self.clearbutton, QtCore.SIGNAL("clicked()"), self.complementsequence.clear)
        QtCore.QObject.connect(self.clearbutton, QtCore.SIGNAL("clicked()"), self.id.clear)
        QtCore.QObject.connect(self.clearbutton, QtCore.SIGNAL("clicked()"), self.reversecomplement.clear)
        QtCore.QObject.connect(self.clearbutton, QtCore.SIGNAL("clicked()"), self.seqalphabet.clear)
        QtCore.QObject.connect(self.clearbutton, QtCore.SIGNAL("clicked()"), self.totalaminoacid.clear)
        QtCore.QObject.connect(self.entrez_clear, QtCore.SIGNAL("clicked()"), self.entrez_id.clear)
        QtCore.QObject.connect(self.entrez_clear, QtCore.SIGNAL("clicked()"), self.entrez_email.clear)
        QtCore.QObject.connect(self.entrez_clear, QtCore.SIGNAL("clicked()"), self.entrez_info.clear)
        QtCore.QObject.connect(self.radiobutton_import, QtCore.SIGNAL("toggled(bool)"), self.import_seq1.setEnabled)
        QtCore.QObject.connect(self.radiobutton_import, QtCore.SIGNAL("toggled(bool)"), self.import_seq2.setEnabled)
        QtCore.QObject.connect(self.radiobutton_manual, QtCore.SIGNAL("toggled(bool)"), self.seq1.setEnabled)
        QtCore.QObject.connect(self.radiobutton_manual, QtCore.SIGNAL("toggled(bool)"), self.seq2.setEnabled)
        QtCore.QObject.connect(self.radiobutton_import, QtCore.SIGNAL("toggled(bool)"), self.seq1.setDisabled)
        QtCore.QObject.connect(self.radiobutton_import, QtCore.SIGNAL("toggled(bool)"), self.seq2.setDisabled)
        QtCore.QObject.connect(self.radiobutton_manual, QtCore.SIGNAL("toggled(bool)"), self.import_seq1.setDisabled)
        QtCore.QObject.connect(self.radiobutton_manual, QtCore.SIGNAL("toggled(bool)"), self.import_seq2.setDisabled)
        QtCore.QObject.connect(self.pairwise_clear, QtCore.SIGNAL("clicked()"), self.seq1.clear)
        QtCore.QObject.connect(self.pairwise_clear, QtCore.SIGNAL("clicked()"), self.seq2.clear)
        QtCore.QObject.connect(self.pairwise_clear, QtCore.SIGNAL("clicked()"), self.alignment_result.clear)
        QtCore.QObject.connect(self.pairwise_clear, QtCore.SIGNAL("clicked()"), self.list_alignment.clear)
        QtCore.QObject.connect(self.pairwise_clear, QtCore.SIGNAL("clicked()"), self.variable_alignment.clear)
        QtCore.QObject.connect(self.pmid_clear, QtCore.SIGNAL("clicked()"), self.pmid.clear)
        QtCore.QObject.connect(self.pmid_clear, QtCore.SIGNAL("clicked()"), self.pmid_email.clear)
        QtCore.QObject.connect(self.pmid_clear, QtCore.SIGNAL("clicked()"), self.pmid_data.clear)
        QtCore.QObject.connect(self.clearbutton, QtCore.SIGNAL("clicked()"), self.insertbox.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "Biopython Application v1.0", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("MainWindow", "Biopython Application v1.0", None, -1))
        self.label_id.setText(QtWidgets.QApplication.translate("MainWindow", "ID / AC Number", None, -1))
        self.label_email.setText(QtWidgets.QApplication.translate("MainWindow", "Email Address", None, -1))
        self.entrez_info_2.setText(QtWidgets.QApplication.translate("MainWindow", "Info", None, -1))
        self.label_type.setText(QtWidgets.QApplication.translate("MainWindow", "Format File", None, -1))
        self.spinner.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "gb", None, -1))
        self.spinner.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "fasta", None, -1))
        self.entrez_fetch.setText(QtWidgets.QApplication.translate("MainWindow", "Fetch !", None, -1))
        self.entrez_clear.setText(QtWidgets.QApplication.translate("MainWindow", "Clear", None, -1))
        self.entrez_save.setText(QtWidgets.QApplication.translate("MainWindow", "Save", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.entreznucleotide), QtWidgets.QApplication.translate("MainWindow", "Entrez Nucleotide", None, -1))
        self.importbutton.setText(QtWidgets.QApplication.translate("MainWindow", "Import", None, -1))
        self.analyzebutton.setText(QtWidgets.QApplication.translate("MainWindow", "Analyze", None, -1))
        self.labelid.setText(QtWidgets.QApplication.translate("MainWindow", "Record ID", None, -1))
        self.labeldescription.setText(QtWidgets.QApplication.translate("MainWindow", "Record Description", None, -1))
        self.labelseqalphabet.setText(QtWidgets.QApplication.translate("MainWindow", "Sequence & Alphabet", None, -1))
        self.labelsequencelength.setText(QtWidgets.QApplication.translate("MainWindow", "Sequence Length", None, -1))
        self.labelcomplementsequence.setText(QtWidgets.QApplication.translate("MainWindow", "Complement Sequence", None, -1))
        self.labeltotalaminoacid.setText(QtWidgets.QApplication.translate("MainWindow", "Total Amino Acid", None, -1))
        self.labelreversecomplement.setText(QtWidgets.QApplication.translate("MainWindow", "Reverse Complement", None, -1))
        self.labelsequence.setText(QtWidgets.QApplication.translate("MainWindow", "Record Sequence", None, -1))
        self.aminoacidbutton.setText(QtWidgets.QApplication.translate("MainWindow", "Amino Acid Details", None, -1))
        self.clearbutton.setText(QtWidgets.QApplication.translate("MainWindow", "Clear", None, -1))
        self.savebutton.setText(QtWidgets.QApplication.translate("MainWindow", "Save", None, -1))
        self.labelimport.setText(QtWidgets.QApplication.translate("MainWindow", "Import Records (.fasta or .gbk)", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sequenceparsing), QtWidgets.QApplication.translate("MainWindow", "Sequence Parsing", None, -1))
        self.label_mode.setText(QtWidgets.QApplication.translate("MainWindow", "Mode", None, -1))
        self.radiobutton_import.setText(QtWidgets.QApplication.translate("MainWindow", "Import", None, -1))
        self.radiobutton_manual.setText(QtWidgets.QApplication.translate("MainWindow", "Manual", None, -1))
        self.label_seq1.setText(QtWidgets.QApplication.translate("MainWindow", "Sequence 1", None, -1))
        self.import_seq1.setText(QtWidgets.QApplication.translate("MainWindow", "Import Seq 1", None, -1))
        self.label_seq2.setText(QtWidgets.QApplication.translate("MainWindow", "Sequence 2", None, -1))
        self.import_seq2.setText(QtWidgets.QApplication.translate("MainWindow", "Import Seq 2", None, -1))
        self.align.setText(QtWidgets.QApplication.translate("MainWindow", "Align !", None, -1))
        self.alignment_label.setText(QtWidgets.QApplication.translate("MainWindow", "Alignment Result", None, -1))
        self.var_alignment_label.setText(QtWidgets.QApplication.translate("MainWindow", "Variable Alignment", None, -1))
        self.list_alignment_label.setText(QtWidgets.QApplication.translate("MainWindow", "List of Variable Alignment", None, -1))
        self.pairwise_clear.setText(QtWidgets.QApplication.translate("MainWindow", "Clear", None, -1))
        self.pairwise_save.setText(QtWidgets.QApplication.translate("MainWindow", "Save", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pairwise2), QtWidgets.QApplication.translate("MainWindow", "Multiple Sequence Alignment", None, -1))
        self.labem_pmid_number.setText(QtWidgets.QApplication.translate("MainWindow", "PMID Number", None, -1))
        self.label_pmid_email.setText(QtWidgets.QApplication.translate("MainWindow", "Email Address", None, -1))
        self.pmid_info.setText(QtWidgets.QApplication.translate("MainWindow", "Info", None, -1))
        self.label_type_2.setText(QtWidgets.QApplication.translate("MainWindow", "Format File", None, -1))
        self.pmid_spinner.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Abstract", None, -1))
        self.pmid_spinner.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "MEDLINE", None, -1))
        self.pmid_spinner.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "XML", None, -1))
        self.pmid_fetch.setText(QtWidgets.QApplication.translate("MainWindow", "Fetch !", None, -1))
        self.pmid_clear.setText(QtWidgets.QApplication.translate("MainWindow", "Clear", None, -1))
        self.pmid_save.setText(QtWidgets.QApplication.translate("MainWindow", "Save", None, -1))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pubmedlounge), QtWidgets.QApplication.translate("MainWindow", "PubMed Lounge", None, -1))

